"""initialization state

Revision ID: 7944ea871abb
Revises: 
Create Date: 2024-03-07 20:49:45.986025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7944ea871abb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_category_name'), ['name'], unique=True)

    op.create_table('transaction_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_status_name'), ['name'], unique=True)

    op.create_table('transaction_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_tag_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=120), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('account_type', sa.String(length=64), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_account_account_number'), ['account_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_bank_account_account_type'), ['account_type'], unique=False)

    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_input', sa.String(length=1000), nullable=True),
    sa.Column('bot_response', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('transaction_type', sa.String(length=64), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['bank_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_tag_association',
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['transaction_tag.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_tag_association')
    op.drop_table('transactions')
    op.drop_table('notification')
    op.drop_table('conversation')
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_account_account_type'))
        batch_op.drop_index(batch_op.f('ix_bank_account_account_number'))

    op.drop_table('bank_account')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('transaction_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_tag_name'))

    op.drop_table('transaction_tag')
    with op.batch_alter_table('transaction_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_status_name'))

    op.drop_table('transaction_status')
    with op.batch_alter_table('transaction_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_category_name'))

    op.drop_table('transaction_category')
    # ### end Alembic commands ###
